"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Locale = "ko" | "en";

type Dictionary = Record<string, string>;

const dictionaries: Record<Locale, Dictionary> = {
  ko: {
    language: "한국어",
    language_short: "KO",
    app_description: "로컬 자동화 플랫폼",
    input_placeholder: "명령을 입력하세요...",
    run: "실행",
    running: "실행 중...",
    pending: "대기 중",
    running_status: "실행 중",
    done: "완료",
    failed: "실패",
    approval_required: "승인 필요",
    cancelled: "취소됨",
    deleting: "삭제 중...",
    delete: "삭제",
    open_link: "링크 열기",
    search_results: "검색 결과",
    preview: "크롤링 미리보기",
    open: "열기",
    close: "닫기",
    failure_reason: "실패 이유",
    execution_failed: "실행에 실패했습니다.",
    message_draft: "메시지 초안",
    email_draft: "이메일 초안",
    recipient: "수신자",
    subject: "제목",
    body: "본문",
    schedule_created: "스케줄 생성됨",
    schedule_draft: "스케줄 초안 준비됨",
    approvals_title: "승인 대기 작업",
    approvals_desc: "중간 이상 위험도로 분류된 작업은 확인 후 실행됩니다.",
    approve: "승인",
    reject: "거부",
    schedules_title: "스케줄",
    schedules_desc: "cron 형식으로 반복 작업을 등록할 수 있습니다.",
    name: "이름",
    command_to_run: "실행할 명령",
    adding_schedule: "등록 중...",
    add_schedule: "스케줄 추가",
    next_run: "다음 실행",
    mobile_connection_on: "모바일 연결 켜짐",
    mobile_connection_off: "모바일 연결 꺼짐",
    mobile_connection_component_needed: "모바일 연결 구성요소 필요",
    ai_connected: "AI 연결됨",
    ai_not_set: "AI 미설정",
    mobile_connection: "모바일 연결",
    settings: "설정",
    mobile_connection_not_ready: "모바일 연결이 아직 준비되지 않았습니다",
    mobile_connection_not_ready_desc: "Quick Tunnel 또는 정식 Tunnel 중 하나를 선택해서 모바일에서 이 기기에 접속할 수 있게 설정할 수 있습니다.",
    choose_mobile_connection: "눌러서 모바일 연결 방식 설정하기",
    mobile_auth_expired: "모바일 연결 인증이 만료되었습니다",
    mobile_auth_expired_desc: "PC에서 새 페어링 토큰을 확인한 뒤 모바일 앱에서 다시 연결해 주세요.",
    no_history: "아직 실행 내역이 없습니다.",
    completed_history: "완료된 내역",
    completed_desc: "아래에서 결과 카테고리를 골라 바로 확인하고 삭제할 수 있습니다.",
    deselect: "선택 해제",
    select_all: "전체 선택",
    delete_selected: "선택 삭제",
    all: "전체",
    failures_only_desc: "실패한 실행 내역만 따로 보고, 여러 개 선택해서 한 번에 삭제할 수 있습니다.",
    no_items_in_category: "이 카테고리에는 내역이 없습니다.",
    remote_connection_setup: "원격 연결 설정",
    remote_connection_setup_desc: "모바일 연결과 외부 접속을 위해 터널 연결 방식을 선택할 수 있습니다.",
    close_label: "닫기",
    current_status: "현재 상태",
    tunnel_connected_desc: "모바일 연결이 준비되어 있습니다.",
    quick_not_connected_desc: "Quick Tunnel이 선택되어 있지만 아직 연결되지 않았습니다.",
    cloudflare_not_connected_desc: "정식 Tunnel이 선택되어 있지만 아직 연결되지 않았습니다.",
    no_remote_mode_desc: "아직 원격 연결 방식이 선택되지 않았습니다.",
    ai_fallback: "AI fallback",
    ai_key_saved: "AI key가 저장되어 있습니다.",
    ai_key_not_set: "AI key가 아직 설정되지 않았습니다.",
    storage_location: "저장 위치",
    quick_tunnel_desc: "가장 빠르게 연결합니다. 토큰 없이 임시 주소를 발급받습니다.",
    cloudflare_tunnel_short_desc: "Cloudflare 토큰 기반으로 더 안정적인 주소를 설정합니다.",
    open_connection_setup: "연결 설정 열기",
    open_ai_setup: "AI key 설정",
    open_mobile_pair: "모바일 연결 화면 보기",
    setup_title: "Sigorjob 설정",
    setup_desc: "외부에서 이 기기에 접속하려면 Cloudflare 터널이 필요합니다.",
    cloudflare_tunnel_title: "Cloudflare 터널이란?",
    cloudflare_tunnel_desc: "포트포워딩 없이 외부에서 이 기기로 안전하게 접속할 수 있게 해주는 무료 서비스입니다. 모바일 앱에서 명령을 보낼 때 사용됩니다.",
    quick_tunnel: "Quick Tunnel",
    quick_tunnel_long: "가장 쉽게 시작하는 방식입니다. 토큰 없이 바로 임시 URL을 발급받습니다.",
    quick_tunnel_note: "테스트와 빠른 연결에 적합하지만, 주소가 바뀔 수 있습니다.",
    named_tunnel: "정식 Tunnel",
    named_tunnel_long: "Cloudflare 계정의 터널 토큰을 사용합니다.",
    named_tunnel_note: "더 안정적인 운영에 적합하지만, Cloudflare 대시보드에서 터널과 hostname/route 설정이 필요합니다.",
    packaged_note: "일반적인 데스크톱 앱 배포본은 `cloudflared`를 함께 포함합니다. 직접 소스에서 실행 중인 경우에만 별도 설치가 필요할 수 있습니다.",
    open_cloudflare_dashboard: "Cloudflare 대시보드 열기 →",
    ai_fallback_setup: "AI fallback 설정",
    ai_fallback_desc: "규칙 기반으로 처리되지 않는 요청은 Anthropic API key가 있어야 AI가 대신 해석할 수 있습니다.",
    anthropic_api_key: "Anthropic API key",
    ai_usage_desc: "planning, summary, result review에 사용됩니다.",
    keychain: "macOS Keychain",
    local_secure_config: "local secure config",
    configured: "Configured",
    not_set: "Not set",
    save_ai_key: "AI key 저장",
    saving: "Saving...",
    remove: "삭제",
    api_key_guide: "API key 발급 안내",
    api_key_guide_desc: "현재 이 앱의 AI fallback은 Anthropic API key를 사용합니다. 아래 링크에서 발급 위치를 바로 확인할 수 있습니다.",
    permissions_title: "권한 및 연결 상태",
    permissions_desc: "연결된 기능이나 앱이 어떤 권한을 쓰는지 확인하고, 필요하면 직접 허용 상태를 바꿀 수 있습니다.",
    permission_allowed: "허용됨",
    permission_not_allowed: "미허용",
    currently_supported: "현재 지원됨",
    reference_link: "참고용 링크",
    issuance_guide: "발급 안내",
    anthropic_issue_desc: "Console 계정을 만든 뒤 Account Settings에서 API key를 생성합니다.",
    openai_issue_desc: "Platform 대시보드에서 API key를 만들고 관리할 수 있습니다.",
    gemini_issue_desc: "Google AI Studio에서 Gemini API key를 생성할 수 있습니다.",
    start_quick_tunnel: "Quick Tunnel 시작하기",
    setup_named_tunnel: "정식 Tunnel 설정하기",
    use_local_only_later: "나중에 설정하기 (로컬에서만 사용)",
    enter_tunnel_token: "터널 토큰 입력",
    tunnel_token_desc: "Cloudflare Zero Trust → Networks → Tunnels에서 토큰을 복사하세요.",
    tunnel_token: "터널 토큰",
    connect: "연결하기",
    back: "← 이전",
    connecting_tunnel: "터널 연결 중...",
    up_to_20_seconds: "최대 20초가 소요될 수 있습니다.",
    connection_complete: "연결 완료!",
    tunnel_url: "터널 URL",
    open_remotely_desc: "이 URL로 외부에서 접속할 수 있습니다. 모바일 연결 화면에서 QR 코드를 확인하세요.",
    start: "시작하기",
    loading_mobile_pair: "모바일 연결 정보를 불러오는 중입니다...",
    mobile_app_connect: "모바일 앱 연결",
    mobile_app_connect_desc: "이 화면에서 모바일 앱에 넣을 연결 정보를 확인할 수 있습니다.",
    retry_loading_pair: "다시 불러오기",
    remote_component_unavailable: "Remote access component is unavailable.",
    tunnel_starting: "모바일 연결 준비 중입니다. 잠시 후 다시 확인해주세요.",
    current_mode: "현재 선택된 방식",
    go_to_setup: "설정 화면으로 이동",
    pairing_ready: "페어링 준비가 완료되었습니다",
    pairing_ready_desc: "아래 URL과 토큰을 모바일 앱에서 입력하면 바로 연결할 수 있습니다.",
    qr_ready_desc: "모바일 앱에서 QR 스캔으로 바로 연결할 수 있습니다.",
    url_copied: "URL 복사됨",
    copy_url: "URL 복사",
    quick_url_note: "Quick Tunnel 주소는 임시 주소라 다시 시작하면 바뀔 수 있습니다.",
    connection_method: "연결 방법",
    connection_method_desc: "QR을 스캔하거나, 모바일 앱에서 `수동 입력으로 연결`을 눌러 URL과 토큰을 직접 붙여 넣으세요.",
    auth_token_manual: "인증 토큰 (수동 입력용)",
    copied: "복사됨",
    copy: "복사",
    mobile_steps: "모바일에서 연결하는 순서",
    mobile_step_1: "모바일 앱에서 QR 스캔 또는 `수동 입력으로 연결`을 선택합니다.",
    mobile_step_2: "QR을 스캔하거나 위 터널 URL을 붙여 넣습니다.",
    mobile_step_3: "필요하면 인증 토큰을 붙여 넣고 연결합니다.",
    back_to_main: "← 메인으로",
  },
  en: {
    language: "English",
    language_short: "EN",
    app_description: "Local automation platform",
    input_placeholder: "Enter a command...",
    run: "Run",
    running: "Running...",
    pending: "Pending",
    running_status: "Running",
    done: "Done",
    failed: "Failed",
    approval_required: "Approval required",
    cancelled: "Cancelled",
    deleting: "Deleting...",
    delete: "Delete",
    open_link: "Open link",
    search_results: "Search results",
    preview: "Preview",
    open: "Open",
    close: "Close",
    failure_reason: "Failure reason",
    execution_failed: "Execution failed.",
    message_draft: "Message draft",
    email_draft: "Email draft",
    recipient: "Recipient",
    subject: "Subject",
    body: "Body",
    schedule_created: "Schedule created",
    schedule_draft: "Schedule draft ready",
    approvals_title: "Pending approvals",
    approvals_desc: "Tasks marked with medium or higher risk run only after confirmation.",
    approve: "Approve",
    reject: "Reject",
    schedules_title: "Schedules",
    schedules_desc: "Register recurring tasks with cron format.",
    name: "Name",
    command_to_run: "Command to run",
    adding_schedule: "Adding...",
    add_schedule: "Add schedule",
    next_run: "Next run",
    mobile_connection_on: "Mobile connection on",
    mobile_connection_off: "Mobile connection off",
    mobile_connection_component_needed: "Mobile component needed",
    ai_connected: "AI connected",
    ai_not_set: "AI not set",
    mobile_connection: "Mobile Connect",
    settings: "Settings",
    mobile_connection_not_ready: "Mobile connection is not ready yet",
    mobile_connection_not_ready_desc: "Choose Quick Tunnel or Named Tunnel so your phone can connect to this device.",
    choose_mobile_connection: "Click to configure mobile connection",
    mobile_auth_expired: "Mobile connection authentication expired",
    mobile_auth_expired_desc: "Check the new pairing token on your PC, then reconnect from the mobile app.",
    no_history: "No execution history yet.",
    completed_history: "Completed history",
    completed_desc: "Choose a result category below to review and delete items.",
    deselect: "Deselect",
    select_all: "Select all",
    delete_selected: "Delete selected",
    all: "All",
    failures_only_desc: "You can focus on failed items and delete several at once.",
    no_items_in_category: "There are no items in this category.",
    remote_connection_setup: "Remote connection setup",
    remote_connection_setup_desc: "Choose a tunnel mode for mobile access and remote connection.",
    close_label: "Close",
    current_status: "Current status",
    tunnel_connected_desc: "Mobile connection is ready.",
    quick_not_connected_desc: "Quick Tunnel is selected but not connected yet.",
    cloudflare_not_connected_desc: "Named Tunnel is selected but not connected yet.",
    no_remote_mode_desc: "No remote connection mode has been selected yet.",
    ai_fallback: "AI fallback",
    ai_key_saved: "An AI key is stored.",
    ai_key_not_set: "No AI key has been configured yet.",
    storage_location: "Storage",
    quick_tunnel_desc: "Fastest option. Creates a temporary address without a token.",
    cloudflare_tunnel_short_desc: "Uses a Cloudflare token for a more stable address.",
    open_connection_setup: "Open connection setup",
    open_ai_setup: "Set AI key",
    open_mobile_pair: "Open mobile pairing",
    setup_title: "Sigorjob Setup",
    setup_desc: "Cloudflare Tunnel is required if you want to access this device remotely.",
    cloudflare_tunnel_title: "What is Cloudflare Tunnel?",
    cloudflare_tunnel_desc: "It lets you reach this device securely from outside without port forwarding. The mobile app uses it to send commands.",
    quick_tunnel: "Quick Tunnel",
    quick_tunnel_long: "The easiest way to start. It creates a temporary URL without a token.",
    quick_tunnel_note: "Good for testing and quick access, but the address can change.",
    named_tunnel: "Named Tunnel",
    named_tunnel_long: "Uses a Cloudflare account tunnel token.",
    named_tunnel_note: "Better for stable operation, but you need tunnel and hostname/route setup in the Cloudflare dashboard.",
    packaged_note: "Packaged desktop builds usually include `cloudflared`. You may need a separate installation only when running from source.",
    open_cloudflare_dashboard: "Open Cloudflare dashboard →",
    ai_fallback_setup: "AI fallback setup",
    ai_fallback_desc: "Requests that cannot be handled by rules need an Anthropic API key so AI can interpret them.",
    anthropic_api_key: "Anthropic API key",
    ai_usage_desc: "Used for planning, summaries, and result review.",
    keychain: "macOS Keychain",
    local_secure_config: "local secure config",
    configured: "Configured",
    not_set: "Not set",
    save_ai_key: "Save AI key",
    saving: "Saving...",
    remove: "Remove",
    api_key_guide: "API key guide",
    api_key_guide_desc: "This app currently uses an Anthropic API key for AI fallback. Use the links below to see where to create keys.",
    permissions_title: "Permissions and connection status",
    permissions_desc: "Review which connected features or apps need access, and toggle permission states when needed.",
    permission_allowed: "Allowed",
    permission_not_allowed: "Not allowed",
    currently_supported: "Currently supported",
    reference_link: "Reference",
    issuance_guide: "How to get one",
    anthropic_issue_desc: "Create a Console account, then generate an API key from Account Settings.",
    openai_issue_desc: "Create and manage API keys from the Platform dashboard.",
    gemini_issue_desc: "Create a Gemini API key in Google AI Studio.",
    start_quick_tunnel: "Start Quick Tunnel",
    setup_named_tunnel: "Set up Named Tunnel",
    use_local_only_later: "Maybe later (local only)",
    enter_tunnel_token: "Enter tunnel token",
    tunnel_token_desc: "Copy the token from Cloudflare Zero Trust → Networks → Tunnels.",
    tunnel_token: "Tunnel token",
    connect: "Connect",
    back: "← Back",
    connecting_tunnel: "Connecting tunnel...",
    up_to_20_seconds: "This can take up to 20 seconds.",
    connection_complete: "Connected!",
    tunnel_url: "Tunnel URL",
    open_remotely_desc: "You can access this device through this URL. Check the mobile pairing screen for the QR code.",
    start: "Start",
    loading_mobile_pair: "Loading mobile pairing information...",
    mobile_app_connect: "Connect mobile app",
    mobile_app_connect_desc: "Use this screen to check the information needed by the mobile app.",
    retry_loading_pair: "Retry",
    remote_component_unavailable: "Remote access component is unavailable.",
    tunnel_starting: "Mobile connection is starting. Please check again shortly.",
    current_mode: "Current mode",
    go_to_setup: "Go to setup",
    pairing_ready: "Pairing is ready",
    pairing_ready_desc: "Enter the URL and token below in the mobile app to connect right away.",
    qr_ready_desc: "You can connect instantly by scanning this QR code in the mobile app.",
    url_copied: "URL copied",
    copy_url: "Copy URL",
    quick_url_note: "Quick Tunnel addresses are temporary and may change after restart.",
    connection_method: "Connection method",
    connection_method_desc: "Scan the QR code, or tap manual input in the mobile app and paste the URL and token directly.",
    auth_token_manual: "Auth token (for manual input)",
    copied: "Copied",
    copy: "Copy",
    mobile_steps: "How to connect from mobile",
    mobile_step_1: "In the mobile app, choose QR scan or manual input.",
    mobile_step_2: "Scan the QR code or paste the tunnel URL.",
    mobile_step_3: "If needed, paste the auth token and connect.",
    back_to_main: "← Back to main",
  },
};

type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, fallback?: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);
const LOCALE_STORAGE_KEY = "sigorjob-locale";
const LEGACY_LOCALE_STORAGE_KEY = "agent-platform-locale";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("ko");

  useEffect(() => {
    const saved =
      window.localStorage.getItem(LOCALE_STORAGE_KEY) ??
      window.localStorage.getItem(LEGACY_LOCALE_STORAGE_KEY);
    if (saved === "ko" || saved === "en") {
      setLocaleState(saved);
      window.localStorage.setItem(LOCALE_STORAGE_KEY, saved);
      document.documentElement.lang = saved;
      return;
    }
    const browserLocale = navigator.language.toLowerCase().startsWith("ko") ? "ko" : "en";
    setLocaleState(browserLocale);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, browserLocale);
    document.documentElement.lang = browserLocale;
  }, []);

  const setLocale = (next: Locale) => {
    setLocaleState(next);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, next);
    document.documentElement.lang = next;
  };

  const value = useMemo<LanguageContextValue>(
    () => ({
      locale,
      setLocale,
      t: (key, fallback) => dictionaries[locale][key] ?? fallback ?? key,
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
