"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Locale = "ko" | "en";

type Dictionary = Record<string, string>;

const dictionaries: Record<Locale, Dictionary> = {
  ko: {
    language: "한국어",
    language_short: "KO",
    app_description: "로컬 자동화 플랫폼",
    input_placeholder: "명령을 입력하세요...",
    run: "실행",
    running: "실행 중...",
    pending: "대기 중",
    running_status: "실행 중",
    done: "완료",
    failed: "실패",
    needs_setup: "연결 필요",
    needs_clarification: "추가 질문 필요",
    approval_required: "승인 필요",
    cancelled: "취소됨",
    cancel: "취소",
    deleting: "삭제 중...",
    delete: "삭제",
    open_link: "링크 열기",
    search_results: "검색 결과",
    preview: "크롤링 미리보기",
    open: "열기",
    close: "닫기",
    failure_reason: "실패 이유",
    execution_failed: "실행에 실패했습니다.",
    message_draft: "메시지 초안",
    email_draft: "이메일 초안",
    ai_continued: "AI가 이어서 다듬음",
    continue_with_ai: "AI로 이어서 처리",
    ai_continuation_plan: "AI 후속 처리",
    ai_followup_step: "후속 작업",
    step: "단계",
    recipient: "수신자",
    subject: "제목",
    body: "본문",
    schedule_created: "스케줄 생성됨",
    schedule_draft: "스케줄 초안 준비됨",
    approvals_title: "확인 필요한 작업",
    approvals_desc: "실수 위험이 있는 작업은 여기서 확인한 뒤 진행됩니다.",
    approve: "승인",
    approving: "승인 중...",
    reject: "거부",
    rejecting: "거부 중...",
    approval_modal_title: "계속하기 전에 확인해 주세요",
    approval_reason: "승인이 필요한 이유",
    approval_reason_fallback: "이 작업은 계속 진행하려면 명시적인 허용이 필요합니다.",
    task_rejected_message: "승인이 거부되어 작업이 취소되었습니다.",
    schedules_title: "스케줄",
    schedules_desc: "cron 형식으로 반복 작업을 등록할 수 있습니다.",
    name: "이름",
    command_to_run: "실행할 명령",
    adding_schedule: "등록 중...",
    add_schedule: "스케줄 추가",
    next_run: "다음 실행",
    mobile_connection_on: "모바일 연결 켜짐",
    mobile_connection_off: "모바일 연결 꺼짐",
    mobile_connection_component_needed: "모바일 연결 준비 필요",
    turn_on_tunnel: "모바일 연결 켜기",
    open_mobile_connection: "모바일 연결 화면",
    mobile_component_desc: "휴대폰에서 쓰려면 연결 준비를 먼저 확인해야 합니다.",
    mobile_ready_desc: "휴대폰에서 바로 붙을 수 있도록 연결이 준비되어 있습니다.",
    mobile_off_desc: "아직 휴대폰 연결이 꺼져 있습니다. 먼저 모바일 연결을 켜주세요.",
    ai_connected: "AI 연결됨",
    ai_ready: "AI 준비됨",
    ai_not_set: "AI 미설정",
    ai_connected_desc: "놓친 요청은 AI가 이어서 처리할 수 있는 상태입니다.",
    ai_ready_desc: "AI 키는 저장됐지만, 실제 사용 확인은 아직 끝나지 않았습니다.",
    ai_not_set_desc: "비AI가 놓친 요청까지 자연스럽게 처리하려면 AI 연결이 필요합니다.",
    ai_verified_desc: "AI를 실제로 써볼 수 있는지 확인까지 끝났습니다.",
    ai_key_saved_not_verified: "AI 키는 저장됐지만, 실제로 쓸 수 있는지 확인은 아직 끝나지 않았습니다.",
    verify_connection: "AI 사용 확인",
    ai_credit_low: "Anthropic API 크레딧이 부족합니다. 결제 페이지에서 크레딧을 충전한 뒤 다시 확인해주세요.",
    ai_auth_failed: "Anthropic API 키를 다시 확인해주세요. 키가 잘못됐거나 더 이상 쓸 수 없을 수 있습니다.",
    ai_network_failed: "Anthropic API에 연결하지 못했습니다. 네트워크 상태를 확인한 뒤 다시 시도해주세요.",
    ai_verify_failed_generic: "AI 사용 확인에 실패했습니다. 상세 내용을 확인한 뒤 다시 시도해주세요.",
    show_ai_error_details: "기술 정보 보기",
    hide_ai_error_details: "기술 정보 숨기기",
    mobile_connection: "모바일 연결",
    settings: "설정",
    ai_label: "AI",
    app_logo: "Sigorjob 로고",
    app_tagline: "누구나 쓰는 자동화. 필요할 때만 AI.",
    connected_short: "연결됨",
    disconnected_short: "꺼짐",
    ready_short: "준비됨",
    not_set_short: "미설정",
    not_ready: "준비 필요",
    mobile_connection_not_ready: "모바일 연결이 아직 준비되지 않았습니다",
    mobile_connection_not_ready_desc: "휴대폰에서 이 기기에 붙을 수 있도록 먼저 연결을 켜주세요.",
    choose_mobile_connection: "눌러서 휴대폰 연결 설정하기",
    mobile_auth_expired: "휴대폰 연결이 만료되었습니다",
    mobile_auth_expired_desc: "PC에서 새 페어링 토큰을 확인한 뒤 모바일 앱에서 다시 연결해 주세요.",
    no_history: "아직 실행 내역이 없습니다.",
    history_short: "내역",
    completed_history: "완료된 내역",
    completed_desc: "아래에서 결과 카테고리를 골라 바로 확인하고 삭제할 수 있습니다.",
    deselect: "선택 해제",
    select_all: "전체 선택",
    delete_selected: "선택 삭제",
    all: "전체",
    failures_only_desc: "실패한 실행 내역만 따로 보고, 여러 개 선택해서 한 번에 삭제할 수 있습니다.",
    no_items_in_category: "이 카테고리에는 내역이 없습니다.",
    remote_connection_setup: "휴대폰 연결 설정",
    remote_connection_setup_desc: "휴대폰에서 이 PC에 붙을 수 있도록 연결 방식을 선택합니다.",
    close_label: "닫기",
    current_status: "현재 상태",
    tunnel_connected_desc: "휴대폰 연결이 준비되어 있습니다.",
    quick_not_connected_desc: "간편 연결이 선택되어 있지만 아직 시작되지 않았습니다.",
    cloudflare_not_connected_desc: "고정 주소 연결이 선택되어 있지만 아직 시작되지 않았습니다.",
    no_remote_mode_desc: "아직 휴대폰 연결 방식이 선택되지 않았습니다.",
    ai_fallback: "AI 도움",
    ai_key_saved: "AI 키가 저장되어 있습니다.",
    ai_key_not_set: "AI 키가 아직 설정되지 않았습니다.",
    storage_location: "저장 위치",
    quick_tunnel_desc: "가장 빠르게 연결합니다. 토큰 없이 임시 주소를 발급받습니다.",
    cloudflare_tunnel_short_desc: "Cloudflare 토큰 기반으로 더 안정적인 주소를 설정합니다.",
    open_connection_setup: "휴대폰 연결 설정",
    open_ai_setup: "AI 설정",
    open_mobile_pair: "모바일 연결 화면 보기",
    setup_title: "Sigorjob 설정",
    setup_desc: "휴대폰에서 이 PC를 쓰려면 먼저 연결을 켜야 합니다.",
    cloudflare_tunnel_title: "Cloudflare 연결이란?",
    cloudflare_tunnel_desc: "포트포워딩 없이 휴대폰에서 이 PC로 안전하게 붙게 해주는 연결 방식입니다.",
    quick_tunnel: "간편 연결",
    quick_tunnel_long: "가장 쉽게 시작하는 방식입니다. 로그인 없이 임시 주소를 바로 만듭니다.",
    quick_tunnel_note: "빠르게 써보기 좋지만, 주소가 다시 바뀔 수 있습니다.",
    named_tunnel: "고정 주소 연결",
    named_tunnel_long: "Cloudflare 계정의 토큰을 사용해 더 안정적인 주소로 연결합니다.",
    named_tunnel_note: "안정적으로 쓰기 좋지만, Cloudflare 대시보드에서 추가 설정이 필요합니다.",
    packaged_note: "배포된 데스크톱 앱에는 보통 필요한 연결 도구가 이미 들어 있습니다. 직접 소스에서 실행할 때만 별도 설치가 필요할 수 있습니다.",
    open_cloudflare_dashboard: "Cloudflare 대시보드 열기 →",
    ai_fallback_setup: "AI 설정",
    ai_fallback_desc: "자동화만으로 처리되지 않는 요청은 AI가 이어서 처리합니다. 이를 위해 Anthropic API 키가 필요합니다.",
    anthropic_api_key: "Anthropic API key",
    ai_usage_desc: "명령 해석, 요약, 결과 점검에 사용됩니다.",
    keychain: "macOS Keychain",
    local_secure_config: "로컬 보안 설정",
    configured: "사용 가능",
    not_set: "설정 안 됨",
    save_ai_key: "AI key 저장",
    saving: "저장 중...",
    remove: "삭제",
    api_key_guide: "API key 발급 안내",
    api_key_guide_desc: "현재 이 앱의 AI fallback은 Anthropic API key를 사용합니다. 아래 링크에서 발급 위치를 바로 확인할 수 있습니다.",
    permissions_title: "권한 관리",
    permissions_desc: "기능별로 어떤 권한이 필요한지 보고, 필요하면 직접 켜고 끌 수 있습니다.",
    permission_allowed: "허용됨",
    permission_not_allowed: "미허용",
    currently_supported: "현재 지원됨",
    reference_link: "참고 링크",
    issuance_guide: "발급 안내",
    anthropic_issue_desc: "Console 계정을 만든 뒤 Account Settings에서 API key를 생성합니다.",
    openai_issue_desc: "Platform 대시보드에서 API key를 만들고 관리할 수 있습니다.",
    gemini_issue_desc: "Google AI Studio에서 Gemini API key를 생성할 수 있습니다.",
    start_quick_tunnel: "간편 연결 시작",
    setup_named_tunnel: "고정 주소 연결 설정",
    use_local_only_later: "나중에 설정하기 (로컬에서만 사용)",
    enter_tunnel_token: "연결 토큰 입력",
    tunnel_token_desc: "Cloudflare Zero Trust → Networks → Tunnels에서 토큰을 복사하세요.",
    tunnel_token: "연결 토큰",
    connect: "연결하기",
    connecting: "연결 중...",
    connection: "연결",
    back: "← 이전",
    connecting_tunnel: "연결 준비 중...",
    up_to_20_seconds: "최대 20초가 소요될 수 있습니다.",
    connection_complete: "연결 완료!",
    tunnel_url: "연결 주소",
    open_remotely_desc: "이 주소로 휴대폰에서 접속할 수 있습니다. 아래 QR 코드나 주소를 사용하세요.",
    start: "시작하기",
    go_back: "뒤로",
    loading_mobile_pair: "휴대폰 연결 정보를 불러오는 중입니다...",
    mobile_app_connect: "휴대폰 연결",
    mobile_app_connect_desc: "이 화면에서 휴대폰 앱에 넣을 연결 정보를 확인할 수 있습니다.",
    retry_loading_pair: "다시 불러오기",
    remote_component_unavailable: "휴대폰 연결 준비가 아직 끝나지 않았습니다.",
    tunnel_starting: "휴대폰 연결을 준비하는 중입니다. 잠시 후 다시 확인해주세요.",
    current_mode: "현재 선택된 연결 방식",
    go_to_setup: "연결 설정으로 이동",
    setup_required: "설정 필요",
    setup_modal_title: "계속하려면 서비스를 연결해 주세요",
    setup_reason: "이 설정이 필요한 이유",
    use_fallback: "링크로 대신하기",
    pairing_ready: "휴대폰 연결 준비가 끝났습니다",
    pairing_ready_desc: "아래 주소와 코드를 휴대폰 앱에 넣으면 바로 연결할 수 있습니다.",
    qr_ready_desc: "휴대폰 앱에서 QR을 스캔하면 바로 연결할 수 있습니다.",
    url_copied: "URL 복사됨",
    copy_url: "URL 복사",
    quick_url_note: "간편 연결 주소는 임시 주소라 다시 시작하면 바뀔 수 있습니다.",
    connection_method: "연결 방법",
    connection_method_desc: "QR을 스캔하거나, 휴대폰 앱에서 `수동 입력으로 연결`을 눌러 주소와 코드를 직접 붙여 넣으세요.",
    auth_token_manual: "연결 코드 (수동 입력용)",
    copied: "복사됨",
    copy: "복사",
    mobile_steps: "휴대폰에서 연결하는 순서",
    mobile_step_1: "휴대폰 앱에서 QR 스캔 또는 `수동 입력으로 연결`을 선택합니다.",
    mobile_step_2: "QR을 스캔하거나 위 터널 URL을 붙여 넣습니다.",
    mobile_step_3: "필요하면 인증 토큰을 붙여 넣고 연결합니다.",
    back_to_main: "← 메인으로",
    execution_area: "실행",
    operations_and_routines: "루틴",
    pending_actions: "처리 중인 작업",
    routine_count: "등록된 루틴",
    recent_failures: "최근 실패",
    control_center: "실행",
    no_active_tasks: "지금 실행 중이거나 승인 대기인 작업이 없습니다.",
    approval_and_queue: "대기",
    recent_history: "최근 내역",
    done_suffix: "건 완료",
    failed_suffix: "건 실패",
    routine_overview: "루틴 한눈에 보기",
    routine_history: "루틴 최근 실행",
    routine_history_empty: "아직 루틴 실행 내역이 충분히 쌓이지 않았습니다.",
    mobile_status_quick_desc: "휴대폰 연결 상태를 확인합니다.",
    ai_status_quick_desc: "AI 사용 가능 상태를 확인합니다.",
    submit_error_auth: "연결이 만료되었어요. 다시 연결한 뒤 한 번 더 시도해주세요.",
    submit_error_generic: "요청을 보내지 못했습니다. 잠시 후 다시 시도해주세요.",
    retry: "재실행",
    routines: "루틴",
    count_suffix: "개",
    schedule_form_desc: "이름, 실행할 내용, 반복 시간을 정하면 루틴으로 저장됩니다.",
    schedule_name_placeholder: "루틴 이름",
    repeat_time_placeholder: "반복 시간",
    last_run: "최근 실행",
    weekday_morning: "평일 오전 9시",
    daily_morning: "매일 오전 8시",
    daily_evening: "매일 저녁 6시",
    connection_guidance: "바로가기",
    mobile_operations: "모바일 운영",
    risk_high: "주의 필요",
    risk_medium: "확인 필요",
    risk_low: "낮음",
    purchase_helper_title: "구매 도우미 안내",
    purchase_helper_desc: "살 수 있는 상품 페이지까지 연결했습니다. 결제 전에 상품 옵션, 배송비, 로그인 상태를 한 번 더 확인하세요.",
    pair_load_error: "휴대폰 연결 정보를 불러오지 못했습니다. 잠시 후 다시 시도해주세요.",
    pair_dependency_missing_desc: "배포된 데스크톱 앱에는 필요한 연결 도구가 보통 자동으로 들어 있습니다. 소스에서 직접 실행 중이라면 cloudflared를 설치하거나 CLOUDFLARED_PATH를 지정한 뒤 다시 시도해주세요.",
    ai_key_saved_verified: "AI key를 저장했고, 실제 연결도 확인했습니다.",
    ai_key_saved_unverified: "AI key는 저장했지만 실제 연결은 아직 확인되지 않았습니다.",
    ai_key_save_failed: "AI key를 저장하지 못했습니다.",
    ai_key_removed: "저장된 AI key를 지웠습니다.",
    ai_key_remove_failed: "저장된 AI key를 지우지 못했습니다.",
    ai_verified_now: "AI를 바로 쓸 수 있는 상태입니다.",
    ai_verify_failed_short: "AI 연결을 확인하지 못했습니다.",
    permission_update_failed: "권한 상태를 바꾸지 못했습니다.",
    test_notification_sent: "테스트 알림을 보냈습니다. 휴대폰 앱을 열어둔 뒤 몇 초 정도 기다려주세요.",
    test_notification_failed: "테스트 알림을 보내지 못했습니다.",
    mobile_disconnected_message: "휴대폰 연결을 종료했습니다.",
    mobile_disconnect_failed: "휴대폰 연결을 종료하지 못했습니다.",
    error_network: "네트워크 연결을 확인한 뒤 다시 시도해주세요.",
    error_timeout: "응답 시간이 초과되었습니다. 잠시 후 다시 시도해주세요.",
    error_load_failed: "화면 정보를 불러오지 못했습니다. 잠시 후 다시 시도해주세요.",
    not_scheduled: "미정",
    command: "명령",
    latest_completed_title: "방금 끝난 작업",
    latest_completed_desc: "실행 직후 작업이 바로 사라져 보이지 않도록 최근 완료 작업을 잠깐 여기에도 남깁니다.",
    routine_empty_desc: "아직 예정된 루틴이 없습니다.",
    ai_setup_short_desc: "AI가 필요할 때 이어서 처리할 수 있도록 준비합니다.",
    api_key_guide_short_desc: "어디서 키를 발급받는지 바로 확인할 수 있습니다.",
    permissions_short_desc: "민감한 기능은 여기서 켜고 끕니다.",
    external_connections_separate_hint: "여기는 서비스가 연결됐는지 보여주는 곳입니다. 실제 실행 허용은 아래 권한 관리에서 따로 켜고 끕니다.",
    connected_services_title: "연결됨 또는 준비됨",
    connected_services_desc: "저장된 연결 정보가 있거나, 바로 쓸 준비가 된 서비스입니다.",
    available_services_title: "연결 가능",
    available_services_desc: "아직 연결되진 않았지만, 이후 연결 흐름이 준비되면 위 목록으로 올라옵니다.",
    connection_permissions_separate_hint: "이 서비스로 실제 작업까지 허용하려면, 아래 권한 관리에서 관련 권한도 함께 켜주세요.",
    core_permissions_title: "핵심 권한",
    core_permissions_desc: "모바일 연결과 AI처럼 사용자가 먼저 체감하는 기능을 여기서 관리합니다.",
    service_permissions_title: "서비스 확장",
    service_permissions_desc: "Gmail, Calendar, MCP 같은 외부 기능에 연결될 때 쓰는 권한입니다.",
    sensitive_permissions_title: "민감한 작업 권한",
    sensitive_permissions_desc: "결제, 구매 진행, 외부 서비스 조작처럼 실수 비용이 큰 기능은 여기서 별도로 관리하세요.",
    advanced_permissions_title: "고급 권한",
    advanced_permissions_desc: "드물게 쓰거나 확장 기능에 가까운 권한은 여기에서만 펼쳐서 봅니다.",
    show_advanced_permissions: "고급 권한 보기",
    hide_advanced_permissions: "고급 권한 숨기기",
    setup_overview_short: "모바일 연결, AI, 권한을 한곳에서 관리합니다.",
    missing_mobile_tool_desc: "이 앱에서 휴대폰 연결 도구를 찾지 못했습니다.",
    custom_connectors_title: "사용자 정의 커넥터",
    custom_connectors_desc: "서비스별 전용 흐름 대신 공용 capability와 URL 템플릿으로 연결을 추가합니다.",
    custom_connector_id_placeholder: "예: shared_calendar",
    custom_connector_title_placeholder: "예: 공용 캘린더",
    custom_connector_provider_placeholder: "예: custom / mcp / internal",
    custom_connector_url_placeholder: "URL 템플릿, 예: https://calendar.example.com/new?title={title}&dates={dates}",
    custom_connector_title_template_placeholder: "제목 템플릿, 예: {title} 일정 만들기",
    custom_connector_hint: "현재 UI는 create_calendar_event capability만 먼저 지원합니다. {title}, {details}, {dates} 같은 치환값을 쓸 수 있습니다.",
    save_custom_connector: "커넥터 저장",
    custom_connector_saved: "사용자 정의 커넥터를 저장했습니다.",
    custom_connector_save_failed: "사용자 정의 커넥터를 저장하지 못했습니다.",
    custom_connector_deleted: "사용자 정의 커넥터를 삭제했습니다.",
    custom_connector_delete_failed: "사용자 정의 커넥터를 삭제하지 못했습니다.",
    custom_connector_required_fields: "이름과 URL 템플릿을 먼저 입력해주세요.",
    custom_connector_default_description: "설정 화면에서 추가한 사용자 정의 커넥터입니다.",
    show_connector_advanced: "고급 입력 보기",
    hide_connector_advanced: "고급 입력 숨기기",
    connection_status_label: "상태",
    mobile_setup_status_idle: "버튼을 한 번 누른 뒤 몇 초 정도 기다려 연결이 열리는지 확인해주세요.",
    mobile_setup_short_desc: "연결 방식을 고르고 바로 시작하세요.",
    connection_guidance_short_desc: "연결을 나중에 켜고 로컬에서만 먼저 써볼 수도 있습니다.",
    source_requires_cloudflared: "소스 실행 환경이라면 cloudflared 설치가 필요할 수 있습니다.",
    token_ready_note: "Cloudflare 쪽 설정이 끝난 토큰만 연결됩니다.",
    mobile_operations_short_desc: "테스트 알림을 보내거나 연결을 끊고 다시 시작할 수 있습니다.",
    connect_failed: "연결에 실패했습니다. 설정을 확인해주세요.",
    backend_unreachable: "백엔드에 연결할 수 없습니다. 앱이 실행 중인지 확인해주세요.",
    backend_startup_failed_title: "백엔드 시작에 실패했습니다",
    backend_startup_failed_desc: "앱 화면은 열렸지만 내부 백엔드를 붙이지 못했습니다. 아래 원인과 로그 파일 경로를 먼저 확인해주세요.",
    backend_startup_log_path: "로그 파일",
    mobile_tool_missing_title: "휴대폰 연결 준비가 아직 끝나지 않았습니다",
    sending: "보내는 중...",
    disconnecting_short: "연결 끊는 중...",
    send_test_notification: "테스트 알림 보내기",
    disconnect_mobile_connection: "모바일 연결 끊기",
    clarification_placeholder: "답변을 입력하세요...",
    send_answer: "답변 보내기",
    clarification_attempts: "추가 질문",
    custom_command_title: "사용자 정의 명령",
    custom_command_desc: "특정 단어나 문장이 들어오면, 대신 실행할 명령을 연결합니다.",
    custom_command_trigger_placeholder: "예: 합주 준비",
    custom_command_action_placeholder: "예: 구글 캘린더에 합주 일정 추가해줘",
    add_custom_command: "사용자 정의 명령 추가",
    custom_command_saved: "저장된 사용자 정의 명령",
    match_contains: "포함되면 실행",
    match_exact: "완전히 같으면 실행",
    needs_check_short: "확인 필요",
    planned_short: "예정됨",
    connection_manage_hint: "작업에서 바로 사용할 수 있습니다.",
    connection_verify_hint: "연결 정보는 있지만, 아직 확인이 필요합니다.",
    gmail_connect_hint: "실제 이메일 전송을 요청하기 전에 Gmail을 연결해주세요.",
    calendar_connect_hint: "실제 일정 생성을 요청하기 전에 Calendar를 연결해주세요.",
    mcp_connect_hint: "외부 MCP 도구를 위한 공용 기반 연결로 쓰입니다.",
    connection_connect_hint: "관련 작업을 쓰기 전에 먼저 연결해주세요.",
    connection_callback_failed: "연결을 마무리하지 못했습니다. 다시 시도해주세요.",
    connection_pending_message: "연결 완료를 기다리는 중입니다. 로그인 창을 마치면 여기 상태가 갱신됩니다.",
    connection_authorize_failed: "연결 흐름을 시작하지 못했습니다.",
    connection_disconnect_failed: "서비스 연결을 해제하지 못했습니다.",
    external_connections_title: "외부 연결",
    external_connections_desc: "Gmail, Calendar, 앞으로 추가될 MCP 도구를 한곳에서 관리합니다.",
    connect_service: "서비스 연결",
    disconnect_service: "연결 해제",
    connecting_oauth: "연결 중...",
    gmail_connection_title: "Gmail",
    gmail_connection_desc: "이메일 초안 작성과 실제 Gmail 전송에 사용합니다.",
    google_calendar_connection_title: "Google Calendar",
    google_calendar_connection_desc: "일정 생성과 캘린더 확인에 사용합니다.",
    mcp_runtime_connection_title: "MCP Runtime",
    mcp_runtime_connection_desc: "외부 MCP 도구와 프리셋을 연결하는 공용 실행 기반입니다.",
    mcp_presets_title: "MCP 프리셋",
    mcp_presets_desc: "준비된 MCP 번들을 한 번에 설치하거나 제거합니다.",
    mcp_presets_empty: "지금 사용할 수 있는 MCP 프리셋이 없습니다.",
    mcp_preset_install_failed: "MCP 프리셋을 설치하지 못했습니다.",
    mcp_preset_uninstall_failed: "MCP 프리셋을 제거하지 못했습니다.",
    install: "설치",
    uninstall: "제거",
    installing_short: "설치 중...",
    uninstalling_short: "제거 중...",
    installed_short: "설치됨",
    not_installed_short: "설치 안 됨",
    tools_title: "도구",
    tools_desc: "브라우저 자동화 같은 작업에 필요한 로컬 도구를 설치합니다.",
    playwright: "Playwright",
    playwright_desc: "Chromium을 열고 제어하는 브라우저 자동화 작업에 필요합니다.",
    playwright_install_notice: "Playwright 설치에는 Chromium 다운로드가 포함되어 몇 분 정도 걸릴 수 있습니다.",
    playwright_install_failed: "Playwright를 설치하지 못했습니다.",
    playwright_install_success: "Playwright 설치가 완료되었습니다.",
    install_cloudflared_first: "먼저 cloudflared를 설치해주세요.",
    quick_tunnel_label: "간편 연결",
    notification_test_title: "Sigorjob 테스트",
    notification_test_body: "휴대폰이 연결되어 있고 앱이 열려 있다면 몇 초 안에 이 알림이 보여야 합니다.",
  },
  en: {
    language: "English",
    language_short: "EN",
    app_description: "Local automation platform",
    input_placeholder: "Enter a command...",
    run: "Run",
    running: "Running...",
    pending: "Pending",
    running_status: "Running",
    done: "Done",
    failed: "Failed",
    needs_setup: "Needs setup",
    needs_clarification: "Needs clarification",
    approval_required: "Approval required",
    cancelled: "Cancelled",
    cancel: "Cancel",
    deleting: "Deleting...",
    delete: "Delete",
    open_link: "Open link",
    search_results: "Search results",
    preview: "Preview",
    open: "Open",
    close: "Close",
    failure_reason: "Failure reason",
    execution_failed: "Execution failed.",
    message_draft: "Message draft",
    email_draft: "Email draft",
    ai_continued: "Enhanced by AI",
    continue_with_ai: "Continue with AI",
    ai_continuation_plan: "AI continuation",
    ai_followup_step: "Follow-up action",
    step: "Step",
    recipient: "Recipient",
    subject: "Subject",
    body: "Body",
    schedule_created: "Schedule created",
    schedule_draft: "Schedule draft ready",
    approvals_title: "Needs confirmation",
    approvals_desc: "Tasks with a higher chance of mistakes wait here until you confirm them.",
    approve: "Approve",
    approving: "Approving...",
    reject: "Reject",
    rejecting: "Rejecting...",
    approval_modal_title: "Review before continuing",
    approval_reason: "Approval reason",
    approval_reason_fallback: "This action requires explicit permission before it can continue.",
    task_rejected_message: "Approval was rejected. The task was cancelled.",
    schedules_title: "Schedules",
    schedules_desc: "Register recurring tasks with cron format.",
    name: "Name",
    command_to_run: "Command to run",
    adding_schedule: "Adding...",
    add_schedule: "Add schedule",
    next_run: "Next run",
    mobile_connection_on: "Mobile connection on",
    mobile_connection_off: "Mobile connection off",
    mobile_connection_component_needed: "Mobile setup needed",
    turn_on_tunnel: "Turn on mobile access",
    open_mobile_connection: "Open mobile connection",
    mobile_component_desc: "Mobile access needs one more setup step before it can be used.",
    mobile_ready_desc: "Your phone can connect right away.",
    mobile_off_desc: "Mobile access is off. Turn it on first.",
    ai_connected: "AI connected",
    ai_ready: "AI ready",
    ai_not_set: "AI not set",
    ai_connected_desc: "Missed requests can be continued by AI.",
    ai_ready_desc: "The API key is saved, but we have not confirmed real API access yet.",
    ai_not_set_desc: "Connect AI if you want missed non-AI requests to continue naturally.",
    ai_verified_desc: "Real AI access has been confirmed.",
    ai_key_saved_not_verified: "The AI key is saved, but real API access has not been confirmed yet.",
    verify_connection: "Check AI access",
    ai_credit_low: "Your Anthropic API credits are too low. Add credits in Plans & Billing, then try verification again.",
    ai_auth_failed: "Check your Anthropic API key. It may be invalid or no longer active.",
    ai_network_failed: "Could not connect to the Anthropic API. Check your network and try again.",
    ai_verify_failed_generic: "We could not confirm AI access. Check the details and try again.",
    show_ai_error_details: "Show technical details",
    hide_ai_error_details: "Hide technical details",
    mobile_connection: "Mobile Connect",
    settings: "Settings",
    ai_label: "AI",
    app_logo: "Sigorjob logo",
    app_tagline: "Automation for everyone. AI only when needed.",
    connected_short: "Connected",
    disconnected_short: "Off",
    ready_short: "Ready",
    not_set_short: "Not set",
    not_ready: "Needs setup",
    mobile_connection_not_ready: "Mobile connection is not ready yet",
    mobile_connection_not_ready_desc: "Turn on mobile access first so your phone can connect to this device.",
    choose_mobile_connection: "Open mobile setup",
    mobile_auth_expired: "Mobile connection authentication expired",
    mobile_auth_expired_desc: "Check the new pairing token on your PC, then reconnect from the mobile app.",
    no_history: "No execution history yet.",
    history_short: "History",
    completed_history: "Completed history",
    completed_desc: "Choose a result category below to review and delete items.",
    deselect: "Deselect",
    select_all: "Select all",
    delete_selected: "Delete selected",
    all: "All",
    failures_only_desc: "You can focus on failed items and delete several at once.",
    no_items_in_category: "There are no items in this category.",
    remote_connection_setup: "Mobile access setup",
    remote_connection_setup_desc: "Choose how your phone will connect to this device.",
    close_label: "Close",
    current_status: "Current status",
    tunnel_connected_desc: "Mobile connection is ready.",
    quick_not_connected_desc: "Quick Tunnel is selected but not connected yet.",
    cloudflare_not_connected_desc: "Named Tunnel is selected but not connected yet.",
    no_remote_mode_desc: "No remote connection mode has been selected yet.",
    ai_fallback: "AI help",
    ai_key_saved: "An AI key is stored.",
    ai_key_not_set: "No AI key has been configured yet.",
    storage_location: "Storage",
    quick_tunnel_desc: "Fastest option. Creates a temporary address without a token.",
    cloudflare_tunnel_short_desc: "Uses a Cloudflare token for a more stable address.",
    open_connection_setup: "Open mobile setup",
    open_ai_setup: "Open AI settings",
    open_mobile_pair: "Open mobile pairing",
    setup_title: "Sigorjob Setup",
    setup_desc: "Turn on mobile access first if you want to use this PC from your phone.",
    cloudflare_tunnel_title: "What is this connection?",
    cloudflare_tunnel_desc: "It lets your phone reach this PC safely without changing router settings.",
    quick_tunnel: "Quick connect",
    quick_tunnel_long: "The easiest way to start. It creates a temporary address right away.",
    quick_tunnel_note: "Best for quick testing, but the address can change later.",
    named_tunnel: "Stable address",
    named_tunnel_long: "Uses your Cloudflare token for a steadier connection.",
    named_tunnel_note: "Better for long-term use, but needs extra setup in Cloudflare.",
    packaged_note: "Packaged desktop builds usually already include the required connection tool. You may only need a separate install when running from source.",
    open_cloudflare_dashboard: "Open Cloudflare dashboard →",
    ai_fallback_setup: "AI setup",
    ai_fallback_desc: "When simple automation is not enough, AI can continue the task. To do that, add your Anthropic API key here.",
    anthropic_api_key: "Anthropic API key",
    ai_usage_desc: "Used to understand requests, write summaries, and review results.",
    keychain: "macOS Keychain",
    local_secure_config: "local secure storage",
    configured: "Ready",
    not_set: "Not set",
    save_ai_key: "Save AI key",
    saving: "Saving...",
    remove: "Remove",
    api_key_guide: "API key guide",
    api_key_guide_desc: "This app currently uses an Anthropic API key when AI needs to continue a task. Use the links below to see where to create keys.",
    permissions_title: "Permissions",
    permissions_desc: "Review which features need permission and turn them on or off when needed.",
    permission_allowed: "Allowed",
    permission_not_allowed: "Not allowed",
    currently_supported: "Currently supported",
    reference_link: "Reference",
    issuance_guide: "How to get one",
    anthropic_issue_desc: "Create a Console account, then generate an API key from Account Settings.",
    openai_issue_desc: "Create and manage API keys from the Platform dashboard.",
    gemini_issue_desc: "Create a Gemini API key in Google AI Studio.",
    start_quick_tunnel: "Start quick connect",
    setup_named_tunnel: "Set up stable address",
    use_local_only_later: "Maybe later (local only)",
    enter_tunnel_token: "Enter connection token",
    tunnel_token_desc: "Copy the token from Cloudflare Zero Trust → Networks → Tunnels.",
    tunnel_token: "Connection token",
    connect: "Connect",
    connecting: "Connecting...",
    connection: "Connection",
    back: "← Back",
    connecting_tunnel: "Preparing connection...",
    up_to_20_seconds: "This can take up to 20 seconds.",
    connection_complete: "Connected!",
    tunnel_url: "Connection address",
    open_remotely_desc: "Your phone can use this address to reach this device.",
    start: "Start",
    go_back: "Back",
    loading_mobile_pair: "Loading phone connection details...",
    mobile_app_connect: "Connect your phone",
    mobile_app_connect_desc: "Use this screen to see the details your phone app needs.",
    retry_loading_pair: "Retry",
    remote_component_unavailable: "The phone connection tool is not ready yet.",
    tunnel_starting: "Mobile access is being prepared. Please check again shortly.",
    current_mode: "Current connection type",
    go_to_setup: "Open setup",
    setup_required: "Setup required",
    setup_modal_title: "Connect a service to continue",
    setup_reason: "Why this is needed",
    use_fallback: "Use fallback link",
    pairing_ready: "Your phone can connect now",
    pairing_ready_desc: "Enter the address and code below in the phone app to connect right away.",
    qr_ready_desc: "You can connect right away by scanning this QR code in the phone app.",
    url_copied: "URL copied",
    copy_url: "Copy URL",
    quick_url_note: "Quick connect addresses are temporary and may change after restart.",
    connection_method: "How to connect",
    connection_method_desc: "Scan the QR code, or choose manual input in the phone app and paste the address and code.",
    auth_token_manual: "Connection code (manual input)",
    copied: "Copied",
    copy: "Copy",
    mobile_steps: "How to connect from your phone",
    mobile_step_1: "In the mobile app, choose QR scan or manual input.",
    mobile_step_2: "Scan the QR code or paste the tunnel URL.",
    mobile_step_3: "If needed, paste the auth token and connect.",
    back_to_main: "← Back to main",
    execution_area: "Run",
    operations_and_routines: "Routines",
    pending_actions: "In progress",
    routine_count: "Routines",
    recent_failures: "Recent failures",
    control_center: "Run",
    no_active_tasks: "There are no running or waiting tasks right now.",
    approval_and_queue: "Waiting",
    recent_history: "Recent history",
    done_suffix: " done",
    failed_suffix: " failed",
    routine_overview: "Routine overview",
    routine_history: "Recent routine runs",
    routine_history_empty: "There is not enough routine history yet.",
    mobile_status_quick_desc: "Shows whether your phone can connect right now.",
    ai_status_quick_desc: "Shows whether AI can continue tasks right now.",
    submit_error_auth: "The connection expired. Reconnect and try again.",
    submit_error_generic: "Could not send the request. Please try again shortly.",
    retry: "Retry",
    routines: "Routines",
    count_suffix: "",
    schedule_form_desc: "Save a routine with a name, command, and repeat time.",
    schedule_name_placeholder: "Routine name",
    repeat_time_placeholder: "Repeat time",
    last_run: "Last run",
    weekday_morning: "Weekdays 9 AM",
    daily_morning: "Every day 8 AM",
    daily_evening: "Every day 6 PM",
    connection_guidance: "Shortcuts",
    mobile_operations: "Mobile tools",
    risk_high: "Caution",
    risk_medium: "Review",
    risk_low: "Low",
    purchase_helper_title: "Purchase helper",
    purchase_helper_desc: "We opened the product page for purchase. Check options, shipping, and sign-in status before you pay.",
    pair_load_error: "Could not load phone connection details. Please try again in a moment.",
    pair_dependency_missing_desc: "Packaged desktop builds usually include the connection tool automatically. If you are running from source, install cloudflared or set CLOUDFLARED_PATH and try again.",
    ai_key_saved_verified: "AI key saved and verified.",
    ai_key_saved_unverified: "The AI key is saved, but real AI access has not been confirmed yet.",
    ai_key_save_failed: "Could not save the AI key.",
    ai_key_removed: "Removed the saved AI key.",
    ai_key_remove_failed: "Could not remove the saved AI key.",
    ai_verified_now: "AI is ready to use.",
    ai_verify_failed_short: "Could not verify AI access.",
    permission_update_failed: "Could not update the permission.",
    test_notification_sent: "A test notification has been queued. Keep the phone app open and wait a few seconds.",
    test_notification_failed: "Could not send a test notification.",
    mobile_disconnected_message: "Phone connection has been turned off.",
    mobile_disconnect_failed: "Could not turn off the phone connection.",
    error_network: "Check your network connection and try again.",
    error_timeout: "The request timed out. Please try again shortly.",
    error_load_failed: "Could not load the screen data. Please try again in a moment.",
    not_scheduled: "TBD",
    command: "Command",
    latest_completed_title: "Just finished",
    latest_completed_desc: "Recent completed tasks stay here briefly so they do not disappear right after execution.",
    routine_empty_desc: "There are no scheduled routines yet.",
    ai_setup_short_desc: "Set up AI so it can continue tasks when needed.",
    api_key_guide_short_desc: "Use these links to see where keys are created.",
    permissions_short_desc: "Turn sensitive features on or off here.",
    external_connections_separate_hint: "This area only shows whether a service is connected. The actual allow/deny switches live in the permission section below.",
    connected_services_title: "Connected or ready",
    connected_services_desc: "These services already have saved connection information or are ready to use.",
    available_services_title: "Available to connect",
    available_services_desc: "These are not connected yet. Once a connection flow exists, they will move into the ready section above.",
    connection_permissions_separate_hint: "If you want to allow real actions with this service, also turn on the related permission below.",
    core_permissions_title: "Core access",
    core_permissions_desc: "Manage the first-run experiences people notice most, like mobile access and AI help.",
    service_permissions_title: "Service extensions",
    service_permissions_desc: "Use these when Gmail, Calendar, or future MCP-style add-ons should be available.",
    sensitive_permissions_title: "Sensitive permissions",
    sensitive_permissions_desc: "Manage payment, purchase, and external service actions separately here.",
    advanced_permissions_title: "Advanced permissions",
    advanced_permissions_desc: "Keep rarely used or developer-oriented permissions tucked away here.",
    show_advanced_permissions: "Show advanced",
    hide_advanced_permissions: "Hide advanced",
    setup_overview_short: "Manage mobile access, AI, and permissions in one place.",
    missing_mobile_tool_desc: "This app could not find the phone connection tool.",
    custom_connectors_title: "Custom connectors",
    custom_connectors_desc: "Add shared connectors with capabilities and URL templates instead of building one-off service flows.",
    custom_connector_id_placeholder: "Example: shared_calendar",
    custom_connector_title_placeholder: "Example: Shared calendar",
    custom_connector_provider_placeholder: "Example: custom / mcp / internal",
    custom_connector_url_placeholder: "URL template, e.g. https://calendar.example.com/new?title={title}&dates={dates}",
    custom_connector_title_template_placeholder: "Title template, e.g. {title} schedule",
    custom_connector_hint: "The first UI only supports the create_calendar_event capability. Use placeholders like {title}, {details}, and {dates}.",
    save_custom_connector: "Save connector",
    custom_connector_saved: "Custom connector saved.",
    custom_connector_save_failed: "Could not save the custom connector.",
    custom_connector_deleted: "Custom connector removed.",
    custom_connector_delete_failed: "Could not remove the custom connector.",
    custom_connector_required_fields: "Enter a name and URL template first.",
    custom_connector_default_description: "User-defined connector added from the settings screen.",
    show_connector_advanced: "Show advanced fields",
    hide_connector_advanced: "Hide advanced fields",
    connection_status_label: "Status",
    mobile_setup_status_idle: "Press the button once, then wait a few seconds to see whether the connection opens.",
    mobile_setup_short_desc: "Choose a connection type and start right away.",
    connection_guidance_short_desc: "You can turn this on later and start with local-only use first.",
    source_requires_cloudflared: "If you are running from source, cloudflared may still need to be installed.",
    token_ready_note: "Only tokens with completed Cloudflare setup can connect.",
    mobile_operations_short_desc: "Send a test notification or disconnect and start again.",
    connect_failed: "Connection failed. Check your settings and try again.",
    backend_unreachable: "Cannot reach the backend. Make sure the app is running.",
    backend_startup_failed_title: "Backend startup failed",
    backend_startup_failed_desc: "The app window opened, but the internal backend did not start. Check the reason and the log file path below first.",
    backend_startup_log_path: "Log file",
    mobile_tool_missing_title: "Phone connection is not ready yet",
    sending: "Sending...",
    disconnecting_short: "Disconnecting...",
    send_test_notification: "Send test notification",
    disconnect_mobile_connection: "Disconnect phone connection",
    clarification_placeholder: "Type your answer...",
    send_answer: "Send answer",
    clarification_attempts: "Follow-up",
    custom_command_title: "Custom command",
    custom_command_desc: "Map a phrase to another command that Sigorjob should run instead.",
    custom_command_trigger_placeholder: "Example: rehearsal prep",
    custom_command_action_placeholder: "Example: add a rehearsal event to Google Calendar",
    add_custom_command: "Add custom command",
    custom_command_saved: "Saved custom commands",
    match_contains: "When included",
    match_exact: "Exact match",
    needs_check_short: "Check",
    planned_short: "Planned",
    connection_manage_hint: "Ready to use in tasks.",
    connection_verify_hint: "Connected info exists, but it still needs to be checked.",
    gmail_connect_hint: "Connect Gmail before asking Sigorjob to send real email.",
    calendar_connect_hint: "Connect Calendar before asking Sigorjob to create real events.",
    mcp_connect_hint: "This will become the shared base for external MCP tools.",
    connection_connect_hint: "Connect this before using related actions.",
    connection_callback_failed: "Could not finish the connection. Try again.",
    connection_pending_message: "Waiting for the connection to finish. Complete the sign-in window, then the status will refresh here.",
    connection_authorize_failed: "Could not start the connection flow.",
    connection_disconnect_failed: "Could not disconnect the service.",
    external_connections_title: "External connections",
    external_connections_desc: "Use one shared place for Gmail, Calendar, and future MCP tools.",
    connect_service: "Connect",
    disconnect_service: "Disconnect",
    connecting_oauth: "Connecting...",
    gmail_connection_title: "Gmail",
    gmail_connection_desc: "Used for drafting emails and sending real Gmail messages.",
    google_calendar_connection_title: "Google Calendar",
    google_calendar_connection_desc: "Used for creating events and checking calendar schedules.",
    mcp_runtime_connection_title: "MCP Runtime",
    mcp_runtime_connection_desc: "Shared runtime base for external MCP tools and presets.",
    mcp_presets_title: "MCP Presets",
    mcp_presets_desc: "Install or remove ready-made MCP bundles with one click.",
    mcp_presets_empty: "No MCP presets are available right now.",
    mcp_preset_install_failed: "Could not install the MCP preset.",
    mcp_preset_uninstall_failed: "Could not uninstall the MCP preset.",
    install: "Install",
    uninstall: "Uninstall",
    installing_short: "Installing...",
    uninstalling_short: "Uninstalling...",
    installed_short: "Installed",
    not_installed_short: "Not installed",
    tools_title: "Tools",
    tools_desc: "Install local tools required for browser automation and similar tasks.",
    playwright: "Playwright",
    playwright_desc: "Required for browser automation tasks that open and control Chromium.",
    playwright_install_notice: "Installing Playwright may take a few minutes because Chromium also needs to be downloaded.",
    playwright_install_failed: "Could not install Playwright.",
    playwright_install_success: "Playwright installation finished.",
    install_cloudflared_first: "Install cloudflared first",
    quick_tunnel_label: "Quick Tunnel",
    notification_test_title: "Sigorjob test",
    notification_test_body: "If your phone is connected and the app is open, you should see this in a few seconds.",
  },
};

type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, fallback?: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);
const LOCALE_STORAGE_KEY = "sigorjob-locale";
const LEGACY_LOCALE_STORAGE_KEY = "agent-platform-locale";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("ko");

  useEffect(() => {
    const saved =
      window.localStorage.getItem(LOCALE_STORAGE_KEY) ??
      window.localStorage.getItem(LEGACY_LOCALE_STORAGE_KEY);
    if (saved === "ko" || saved === "en") {
      setLocaleState(saved);
      window.localStorage.setItem(LOCALE_STORAGE_KEY, saved);
      document.documentElement.lang = saved;
      return;
    }
    const browserLocale = navigator.language.toLowerCase().startsWith("ko") ? "ko" : "en";
    setLocaleState(browserLocale);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, browserLocale);
    document.documentElement.lang = browserLocale;
  }, []);

  const setLocale = (next: Locale) => {
    setLocaleState(next);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, next);
    document.documentElement.lang = next;
  };

  const value = useMemo<LanguageContextValue>(
    () => ({
      locale,
      setLocale,
      t: (key, fallback) => dictionaries[locale][key] ?? fallback ?? key,
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
