#!/usr/bin/env python3
"""Dev harness: orchestrates Codex CLI for structured implementation tasks.

Usage:
    python3 scripts/dev-harness.py --spec scripts/harness-specs/my-task.json
    python3 scripts/dev-harness.py --spec scripts/harness-specs/my-task.json --pr
    python3 scripts/dev-harness.py --spec scripts/harness-specs/my-task.json --dry-run
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SPECS_DIR = PROJECT_ROOT / "scripts" / "harness-specs"
RESULTS_DIR = PROJECT_ROOT / "scripts" / "harness-results"
AGENTS_MD = PROJECT_ROOT / "AGENTS.md"

DEFAULT_TEST_CMD = "cd backend && python3 -m unittest discover -s tests -v"
DEFAULT_MAX_RETRIES = 3
DEFAULT_MODEL = ""  # empty = use Codex default model


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Dev harness — Codex orchestrator")
    p.add_argument("--spec", required=True, help="Path to spec JSON file")
    p.add_argument("--pr", action="store_true", help="Create PR after success")
    p.add_argument("--no-review", action="store_true", help="Skip review step")
    p.add_argument("--max-retries", type=int, default=None, help="Override max retries")
    p.add_argument("--dry-run", action="store_true", help="Print prompt, don't execute")
    p.add_argument("--model", default=None, help="Override Codex model")
    return p.parse_args()


# ---------------------------------------------------------------------------
# Spec
# ---------------------------------------------------------------------------

def load_spec(path: str) -> dict:
    spec_path = Path(path)
    if not spec_path.is_absolute():
        spec_path = PROJECT_ROOT / spec_path
    with open(spec_path) as f:
        spec = json.load(f)

    required = ["id", "title", "goal", "implementation_locations", "test_requirements", "constraints"]
    missing = [k for k in required if k not in spec]
    if missing:
        print(f"ERROR: spec missing required fields: {missing}", file=sys.stderr)
        sys.exit(1)

    spec.setdefault("branch_name", f"harness/{spec['id']}")
    spec.setdefault("base_branch", "main")
    spec.setdefault("max_retries", DEFAULT_MAX_RETRIES)
    spec.setdefault("codex_model", DEFAULT_MODEL)
    spec.setdefault("test_command", DEFAULT_TEST_CMD)
    spec.setdefault("test_focus_command", "")
    return spec


# ---------------------------------------------------------------------------
# Result record
# ---------------------------------------------------------------------------

def new_result(spec: dict) -> dict:
    return {
        "spec_id": spec["id"],
        "status": "started",
        "started_at": datetime.now(timezone.utc).isoformat(),
        "finished_at": None,
        "attempts": [],
        "final_branch": spec["branch_name"],
        "final_commit": None,
        "pr_url": None,
        "files_changed": [],
        "error": None,
    }


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def git(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        check=check,
    )


def setup_branch(spec: dict) -> None:
    base = spec["base_branch"]
    branch = spec["branch_name"]

    existing = git("branch", "--list", branch, check=False)
    if branch in (existing.stdout or ""):
        git("checkout", branch)
        print(f"  Switched to existing branch: {branch}")
    else:
        git("checkout", base)
        git("checkout", "-b", branch)
        print(f"  Created branch: {branch} from {base}")


def finalize_git(spec: dict) -> str:
    locs = spec["implementation_locations"]
    files = locs.get("new_files", []) + locs.get("modified_files", [])

    if not files:
        diff = git("diff", "--name-only", check=False)
        files = [f.strip() for f in diff.stdout.splitlines() if f.strip()]
        untracked = git("ls-files", "--others", "--exclude-standard", check=False)
        files += [f.strip() for f in untracked.stdout.splitlines() if f.strip()]

    if not files:
        print("  WARNING: no files to commit")
        return ""

    for f in files:
        git("add", f, check=False)

    msg = f"feat: {spec['title']}\n\nSpec: {spec['id']}\nGenerated by dev-harness.py + Codex"
    git("commit", "-m", msg)

    log = git("log", "--oneline", "-1")
    sha = log.stdout.strip().split()[0] if log.stdout.strip() else ""
    print(f"  Committed: {sha}")
    return sha


def create_pr(spec: dict) -> str:
    branch = spec["branch_name"]
    base = spec["base_branch"]

    git("push", "-u", "origin", branch)

    test_checklist = "\n".join(
        f"- [ ] {t['case']}: {t['expected']}" for t in spec["test_requirements"]
    )

    body = f"""## Summary
{spec['goal']}

## Test plan
{test_checklist}

## Harness metadata
- Spec: `{spec['id']}`
- Model: `{spec.get('codex_model', DEFAULT_MODEL)}`

Generated by `dev-harness.py` + Codex
"""

    proc = subprocess.run(
        ["gh", "pr", "create", "--title", f"feat: {spec['title']}", "--body", body, "--base", base],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        check=False,
    )
    url = proc.stdout.strip()
    if proc.returncode != 0:
        print(f"  WARNING: PR creation failed: {proc.stderr.strip()}", file=sys.stderr)
        return ""
    print(f"  PR created: {url}")
    return url


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------

def build_prompt(spec: dict, attempt: int, previous_attempts: list) -> str:
    agents_md = AGENTS_MD.read_text() if AGENTS_MD.exists() else ""

    locs = spec["implementation_locations"]
    new_files = json.dumps(locs.get("new_files", []))
    mod_files = json.dumps(locs.get("modified_files", []))
    test_lines = "\n".join(f"- {t['case']}: {t['expected']}" for t in spec["test_requirements"])
    constraint_lines = "\n".join(f"- {c}" for c in spec["constraints"])

    spec_section = f"""## Spec: {spec['title']}

### Goal
{spec['goal']}

### Implementation locations
New files: {new_files}
Modified files: {mod_files}

### Test requirements
{test_lines}

### Constraints
{constraint_lines}
"""

    if attempt == 1:
        return f"""{agents_md}

---

{spec_section}

Implement the code and tests described in this spec.
Do not add features beyond the spec scope.
Do not modify files not listed in implementation_locations.
After writing the code, run the tests to verify they pass.
"""

    prev = previous_attempts[-1]
    failure_context = _build_failure_context(prev)

    return f"""{agents_md}

---

{spec_section}

---
PREVIOUS ATTEMPT {attempt - 1} FAILED. Fix the issues below.

{failure_context}

Instructions:
- Read the existing code from the previous attempt (it is already on disk)
- Fix only what is broken
- Do not rewrite files from scratch
- Run the tests after fixing to verify
"""


def _build_failure_context(prev: dict) -> str:
    if prev["outcome"] == "test_failed":
        test_r = prev.get("test_result", {})
        focus = test_r.get("focus", {})
        suite = test_r.get("full_suite", {})
        return f"""## Failure type: test_failure

Focused test result: {focus.get('summary_line', 'N/A')}
Full suite result: {suite.get('summary_line', 'N/A')}

Failure details:
{(focus.get('failures_section', '') or suite.get('failures_section', ''))[:3000]}

Full output (last 2000 chars):
{(focus.get('full_output', '') or suite.get('full_output', ''))[-2000:]}
"""

    if prev["outcome"] == "review_rejected":
        return f"""## Failure type: review_rejection

Review feedback:
{prev.get('review_result', {}).get('raw', '')[:2000]}
"""

    return f"## Failure type: {prev.get('outcome', 'unknown')}\n"


# ---------------------------------------------------------------------------
# Codex CLI
# ---------------------------------------------------------------------------

def run_codex_exec(spec: dict, prompt: str, model: str | None = None) -> dict:
    model = model or spec.get("codex_model", DEFAULT_MODEL)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        f.write(prompt)
        prompt_file = f.name

    output_file = str(RESULTS_DIR / f"{spec['id']}_codex_output.txt")

    cmd = [
        "npx", "@openai/codex", "exec",
        "--full-auto",
        "--json",
        "--ephemeral",
        "-C", str(PROJECT_ROOT),
        "-o", output_file,
    ]
    if model:
        cmd.extend(["-m", model])
    cmd.append("-")

    print(f"  Running Codex exec (model={model})...")
    proc = subprocess.run(
        cmd,
        stdin=open(prompt_file),
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        timeout=600,
    )

    os.unlink(prompt_file)

    commands = []
    last_message = ""
    for line in (proc.stdout or "").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            event = json.loads(line)
            if event.get("type") == "command_execution":
                commands.append({
                    "command": event.get("command", ""),
                    "exit_code": event.get("exit_code"),
                })
            if event.get("type") == "agent_message":
                last_message = event.get("content", "")
        except json.JSONDecodeError:
            continue

    if Path(output_file).exists():
        last_message = Path(output_file).read_text().strip() or last_message

    print(f"  Codex exec finished (exit={proc.returncode}, commands={len(commands)})")
    return {
        "exit_code": proc.returncode,
        "commands": commands,
        "last_message": last_message,
        "stderr": (proc.stderr or "")[-1000:],
    }


def run_codex_review(spec: dict) -> str:
    output_file = str(RESULTS_DIR / f"{spec['id']}_review_output.txt")
    review_prompt = (
        f"Review against AGENTS.md conventions and this spec goal: {spec['goal']}. "
        f"Check: architecture compliance, code quality, test coverage. "
        f"Constraints: {'; '.join(spec['constraints'])}. "
        f"List any issues found or say LGTM if all checks pass."
    )

    cmd = [
        "npx", "@openai/codex", "exec", "review",
        "--uncommitted",
        "--json",
        "--ephemeral",
        "-o", output_file,
        review_prompt,
    ]

    print("  Running Codex review...")
    proc = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        timeout=300,
    )

    review_text = ""
    if Path(output_file).exists():
        review_text = Path(output_file).read_text().strip()
    if not review_text:
        review_text = proc.stdout or proc.stderr or ""

    print(f"  Review finished (exit={proc.returncode})")
    return review_text


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------

def run_tests(command: str) -> dict:
    print(f"  Running tests: {command}")
    proc = subprocess.run(
        command,
        shell=True,
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        timeout=120,
    )

    output = (proc.stdout or "") + (proc.stderr or "")

    # Parse pytest-style summary: "X passed, Y failed"
    summary_match = re.search(r"=+ (.*?) =+\s*$", output, re.MULTILINE)
    summary_line = summary_match.group(1) if summary_match else ""

    # Parse unittest-style summary: "Ran N tests" + "OK" or "FAILED (failures=N, errors=N)"
    unittest_ran = re.search(r"Ran (\d+) tests?", output)
    unittest_failures = re.search(r"FAILED \((?:failures=(\d+))?(?:,?\s*errors=(\d+))?\)", output)

    if unittest_ran and not summary_line:
        total = int(unittest_ran.group(1))
        if unittest_failures:
            fail_count = int(unittest_failures.group(1) or 0)
            err_count = int(unittest_failures.group(2) or 0)
            passed = total - fail_count - err_count
            failed = fail_count
            errors = err_count
            summary_line = f"{passed} passed, {failed} failed, {errors} errors (unittest)"
        else:
            passed = total
            failed = 0
            errors = 0
            summary_line = f"{total} passed (unittest)"
    else:
        passed = int(m.group(1)) if (m := re.search(r"(\d+) passed", summary_line)) else 0
        failed = int(m.group(1)) if (m := re.search(r"(\d+) failed", summary_line)) else 0
        errors = int(m.group(1)) if (m := re.search(r"(\d+) error", summary_line)) else 0

    failures_section = ""
    # pytest style
    if "= FAILURES =" in output:
        start = output.index("= FAILURES =")
        end_markers = ["= short test summary", "= ERRORS =", "===="]
        end = len(output)
        for marker in end_markers:
            idx = output.find(marker, start + 20)
            if idx != -1 and idx < end:
                end = idx
        failures_section = output[start:end]
    # unittest style: capture FAIL/ERROR lines
    elif proc.returncode != 0:
        fail_lines = [line for line in output.splitlines()
                      if "FAIL:" in line or "ERROR:" in line or "AssertionError" in line
                      or "Traceback" in line]
        failures_section = "\n".join(fail_lines)

    result = {
        "exit_code": proc.returncode,
        "passed": passed,
        "failed": failed,
        "errors": errors,
        "all_passed": proc.returncode == 0,
        "summary_line": summary_line,
        "failures_section": failures_section[:3000],
        "full_output": output[-3000:],
    }

    status = "PASS" if result["all_passed"] else "FAIL"
    print(f"  Test result: {status} ({passed} passed, {failed} failed, {errors} errors)")
    return result


# ---------------------------------------------------------------------------
# Review parser
# ---------------------------------------------------------------------------

def parse_review(review_text: str) -> dict:
    lower = review_text.lower()

    pass_signals = ["lgtm", "no issues", "all checks pass", "looks good", "approved", "no concerns"]
    fail_signals = ["issue", "problem", "violation", "missing test", "incorrect", "should be fixed", "must be"]

    has_pass = any(s in lower for s in pass_signals)
    has_fail = any(s in lower for s in fail_signals)

    if has_pass and not has_fail:
        return {"passed": True, "issues": [], "raw": review_text}

    issues = []
    for line in review_text.split("\n"):
        stripped = line.strip()
        if stripped and (stripped[0] in "0123456789-*" or stripped.startswith("[")):
            issues.append(stripped)

    return {"passed": has_pass and not has_fail, "issues": issues, "raw": review_text}


# ---------------------------------------------------------------------------
# Main harness loop
# ---------------------------------------------------------------------------

def run_harness(spec: dict, *, pr: bool, no_review: bool, dry_run: bool, model: str | None) -> dict:
    result = new_result(spec)
    max_retries = spec.get("max_retries", DEFAULT_MAX_RETRIES)

    if not dry_run:
        setup_branch(spec)

    for attempt_num in range(1, max_retries + 1):
        print(f"\n{'='*60}")
        print(f"  ATTEMPT {attempt_num}/{max_retries}")
        print(f"{'='*60}")

        attempt_record = {"attempt": attempt_num, "test_result": {}, "review_result": None, "outcome": ""}

        # --- IMPLEMENT ---
        prompt = build_prompt(spec, attempt_num, result["attempts"])

        if dry_run:
            print("\n--- DRY RUN: Generated prompt ---")
            print(prompt)
            print("--- END ---")
            result["status"] = "dry_run"
            return result

        codex_out = run_codex_exec(spec, prompt, model)
        attempt_record["codex_exit_code"] = codex_out["exit_code"]
        attempt_record["codex_commands"] = codex_out["commands"]
        attempt_record["codex_last_message"] = codex_out["last_message"][:2000]

        # --- TEST ---
        focus_cmd = spec.get("test_focus_command")
        if focus_cmd:
            attempt_record["test_result"]["focus"] = run_tests(focus_cmd)
        attempt_record["test_result"]["full_suite"] = run_tests(spec.get("test_command", DEFAULT_TEST_CMD))

        focus_ok = attempt_record["test_result"].get("focus", {}).get("all_passed", True)
        suite_ok = attempt_record["test_result"].get("full_suite", {}).get("all_passed", True)

        if not (focus_ok and suite_ok):
            attempt_record["outcome"] = "test_failed"
            result["attempts"].append(attempt_record)
            print(f"  ATTEMPT {attempt_num}: TESTS FAILED")
            continue

        # --- REVIEW ---
        if no_review:
            attempt_record["review_result"] = {"passed": True, "issues": [], "raw": "skipped"}
            attempt_record["outcome"] = "passed"
            result["attempts"].append(attempt_record)
            print(f"  ATTEMPT {attempt_num}: PASSED (review skipped)")
            break

        review_text = run_codex_review(spec)
        review_parsed = parse_review(review_text)
        attempt_record["review_result"] = review_parsed

        if review_parsed["passed"]:
            attempt_record["outcome"] = "passed"
            result["attempts"].append(attempt_record)
            print(f"  ATTEMPT {attempt_num}: PASSED")
            break
        else:
            attempt_record["outcome"] = "review_rejected"
            result["attempts"].append(attempt_record)
            print(f"  ATTEMPT {attempt_num}: REVIEW REJECTED ({len(review_parsed['issues'])} issues)")
            continue

    # --- FINALIZE ---
    last = result["attempts"][-1] if result["attempts"] else None
    if last and last.get("outcome") == "passed":
        sha = finalize_git(spec)
        result["status"] = "done"
        result["final_commit"] = sha

        diff = git("diff", "--name-only", f"{spec['base_branch']}..HEAD", check=False)
        result["files_changed"] = [f.strip() for f in diff.stdout.splitlines() if f.strip()]

        if pr:
            result["pr_url"] = create_pr(spec)
    else:
        result["status"] = "failed"
        if last:
            result["error"] = f"Failed after {len(result['attempts'])} attempts. Last outcome: {last.get('outcome')}"

    result["finished_at"] = datetime.now(timezone.utc).isoformat()
    return result


# ---------------------------------------------------------------------------
# Result I/O
# ---------------------------------------------------------------------------

def save_result(spec: dict, result: dict) -> Path:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    path = RESULTS_DIR / f"{spec['id']}_result.json"
    with open(path, "w") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)
    return path


def print_summary(result: dict) -> None:
    print(f"\n{'='*60}")
    print("  HARNESS RESULT")
    print(f"{'='*60}")
    print(f"  Status:     {result['status']}")
    print(f"  Attempts:   {len(result['attempts'])}")
    print(f"  Branch:     {result.get('final_branch', 'N/A')}")
    print(f"  Commit:     {result.get('final_commit') or 'N/A'}")
    print(f"  PR:         {result.get('pr_url') or 'N/A'}")
    print(f"  Files:      {', '.join(result.get('files_changed', [])) or 'N/A'}")
    if result.get("error"):
        print(f"  Error:      {result['error']}")
    print(f"{'='*60}")


# ---------------------------------------------------------------------------
# Entry
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    model = args.model
    max_retries = args.max_retries

    spec = load_spec(args.spec)
    if max_retries is not None:
        spec["max_retries"] = max_retries
    if model:
        spec["codex_model"] = model

    print(f"Dev Harness — {spec['title']}")
    print(f"  Spec: {spec['id']}")
    print(f"  Model: {spec.get('codex_model', DEFAULT_MODEL)}")
    print(f"  Max retries: {spec.get('max_retries', DEFAULT_MAX_RETRIES)}")

    result = run_harness(spec, pr=args.pr, no_review=args.no_review, dry_run=args.dry_run, model=model)
    result_path = save_result(spec, result)
    print_summary(result)
    print(f"  Result file: {result_path}")

    sys.exit(0 if result["status"] in ("done", "dry_run") else 1)


if __name__ == "__main__":
    main()
